Parseq/rr
jarnura/purescript-presto-backend pull request #1
Opened 2019-12-05 13:33 UTC by shubhanshu-mani

2019-12-05 13:38 UTC, jarnura requested changes

2019-12-05 13:38 UTC, jarnura commented on src/Presto/Backend/Language/Types/EitherEx.purs
> +--import Presto.Backend.Language.Types.ParSequence (ParError(..))
can you remove the commented code

2019-12-05 13:38 UTC, jarnura commented on src/Presto/Backend/Language/Types/EitherEx.purs
> +-- toParEitherEx :: forall l r. Either l r -> Either ParError r
here also

2019-12-05 13:38 UTC, jarnura commented on src/Presto/Backend/Playback/Entries.purs
> +  , jsonResult  : encode <$> aRes
why this change bro

2019-12-06 09:17 UTC, shubhanshu-mani commented on src/Presto/Backend/Playback/Entries.purs
> +  , jsonResult  : encode <$> aRes
This change was done by mistake

2019-12-11 13:54 UTC, closed without merging