Parseq rr new
jarnura/purescript-presto-backend pull request #2
Opened 2019-12-06 09:20 UTC by shubhanshu-mani

2019-12-10 12:02 UTC, jarnura requested changes

2019-12-10 12:02 UTC, jarnura commented on src/Presto/Backend/Runtime/Interpreter.purs
> +      fn = toCustomEitherEx <<< either (Left <<< fst) (Right <<< fst)
can you change this fn name, remove commented lines

2019-12-10 12:06 UTC, jarnura requested changes

2019-12-10 12:06 UTC, jarnura commented on package-lock.json
>    "name": "purescript-presto-backend",
don't push this file

2019-12-10 13:13 UTC, shubhanshu-mani commented on src/Presto/Backend/Runtime/Interpreter.purs
> +      fn = toCustomEitherEx <<< either (Left <<< fst) (Right <<< fst)
Done

2019-12-11 13:52 UTC, jarnura approved these changes

2019-12-11 13:53 UTC, merged